#!/usr/bin/env python3
"""engine_schema.py — exe-derived engine constants, saved into the library.

Per project policy (2026-07-09): constants mined from the game executable are
legitimate library data — the pipeline must run from game.naz + wlib alone,
and this module is where the exe knowledge lives.

Data files (generated by `watchmen gendata regdump`, shipped in wlib/):
  reg_dump.json            441 classes: props (hash/default/UI caption) +
                           commands (name/hash/handler/argc)
  prop_names_from_reg.json hash -> {classes, ui, default} for all 3602
                           registered property hashes (side lookup for the
                           key_XXXXXXXX names kapow_fragment can't resolve)

Key uses:
  defaults()   fragments only store NON-default values; a node missing
               m_neaseinduration etc. takes the registered default.
  prop_info()  caption/default/classes for an unresolved key_XXXX hash.

Engine numeric constants (sources in docs/ENGINE_CONSTANTS.md):
  BASE_FPS 30.0            engine animation base rate (frameRateScale 1/2/3
                           = FULL/HALF/THIRD of it)
  page blend curve         see anim_state_machine.page_blend_curve (0x77ab7b)
  ANIMATION_CRITERIA enum  see anim_state_machine CRIT_* (exe PUSH pairs)
"""

import json, os, re

_HERE = os.path.dirname(os.path.abspath(__file__))
BASE_FPS = 30.0

_reg = None
_names = None


def reg():
    global _reg
    if _reg is None:
        _reg = json.load(open(os.path.join(_HERE, "reg_dump.json")))
    return _reg


def prop_names():
    global _names
    if _names is None:
        p = os.path.join(_HERE, "prop_names_from_reg.json")
        if os.path.exists(p):
            _names = json.load(open(p))
        else:  # pure aggregation of reg_dump.json - no need to ship the file
            from gen_data import derive_prop_names

            _names = derive_prop_names(reg())
    return _names


def classes():
    """{className: classDict} for all registered classes."""
    return {c["name"]: c for c in reg() if c["name"]}


def _parse_default(s):
    if s is None or "control=" in (s or ""):
        return None  # unset or UI-string reused as default -> none
    if s == "true":
        return True
    if s == "false":
        return False
    try:
        return float(s) if "." in s else int(s)
    except ValueError:
        return s


def defaults(class_name):
    """{propHashHex: defaultValue} for a class (only props that have one).
    Fragments omit default-valued props, so interpreters must fall back to
    these (kapow_fragment key names resolve most hashes to m_* names)."""
    out = {}
    for c in reg():
        if c["name"] == class_name:
            for p in c["props"]:
                v = _parse_default(p["default"])
                if v is not None:
                    out[p["hash"]] = v
    return out


def prop_info(hash_or_key):
    """Info for a prop hash ('0x1a2b..', 'key_1a2b..', or int)."""
    if isinstance(hash_or_key, int):
        h = hash_or_key
    else:
        h = int(str(hash_or_key).replace("key_", "").replace("0x", ""), 16)
    return prop_names().get(hex(h))


def caption(hash_or_key):
    i = prop_info(hash_or_key)
    if not i or not i.get("ui"):
        return None
    m = re.search(r"caption=([^|]*)", i["ui"])
    return m.group(1) if m else None


if __name__ == "__main__":
    import sys

    if len(sys.argv) > 1:
        arg = sys.argv[1]
        if arg.startswith(("0x", "key_")):
            print(json.dumps(prop_info(arg), indent=1))
        else:
            print(json.dumps(defaults(arg), indent=1))
    else:
        cs = classes()
        print(
            len(cs),
            "classes;",
            sum(len(c["props"]) for c in cs.values()),
            "props;",
            sum(len(c["commands"]) for c in cs.values()),
            "commands",
        )
